import numpy as np
import librosa


# mel_filterbank
M_py = librosa.filters.mel(sr=16000, n_fft=512, n_mels=40,
                           fmin=0, fmax=8000, htk=False, norm="slaney").astype(np.float32)
print(f"Mel滤波器读取成功: shape={M_py.shape}, dtype={M_py.dtype}")

TOP_K = 32   # 16 mfcc误差有点大了
header_dir = "out/"  # 输出头文件路径
MEL_BANDS, NUM_BINS = M_py.shape

# =============================
# 生成稀疏化滤波器
# =============================
sparse_filters = []
sparse_indices = []

for i in range(MEL_BANDS):
    row = M_py[i]
    idx = np.argsort(-row)[:TOP_K]  # 取最大 TOP_K 的索引
    vals = row[idx]
    sparse_indices.append(idx)
    sparse_filters.append(vals)

sparse_filters = np.array(sparse_filters, dtype=np.float32)   # shape (MEL_BANDS, TOP_K)
sparse_indices = np.array(sparse_indices, dtype=np.int16)      # shape (MEL_BANDS, TOP_K)

# =============================
# 转置为一维数组，方便 MCU 按行访问
# MCU 索引方式: sparse_filters[i * TOP_K + k]
# =============================
sparse_filters_flat = sparse_filters.flatten()
sparse_indices_flat = sparse_indices.flatten()

# =============================
# 保存为 C 头文件
# =============================
def save_to_header(array, name, filename):
    dtype_map = {np.float32: "float", np.int16: "int16_t", np.int32: "int32_t"}
    dtype_str = dtype_map.get(array.dtype.type, "float")
    
    with open(filename, "w") as f:
        f.write("// Auto-generated by Python\n")
        f.write(f"const {dtype_str} {name}[] = {{\n")
        for i, v in enumerate(array):
            if array.dtype == np.float32:
                f.write(f"{v:.8e}f, ")
            else:
                f.write(f"{v}, ")
            if (i + 1) % 8 == 0:
                f.write("\n")
        f.write("\n};\n")
    print(f"Saved {name} to {filename}")

save_to_header(sparse_filters_flat, "sparse_filters", f"{header_dir}/sparse_filters.h")
save_to_header(sparse_indices_flat, "sparse_indices", f"{header_dir}/sparse_indices.h")

print("稀疏化生成完成:")
print(f"  sparse_filters: shape {sparse_filters_flat.shape}")
print(f"  sparse_indices: shape {sparse_indices_flat.shape}")
print(f"  TOP_K = {TOP_K}, 原始 NUM_BINS = {NUM_BINS}, MEL_BANDS = {MEL_BANDS}")
